### ISSUE TITLE
Doc: docs中に表示されていない画像がある

### ISSUE THREAD

**Issue by moyashipan** [pixiv/charcoal#106]
### できる限り詳細に、不具合の内容と再現方法を報告してください

https://github.com/pixiv/charcoal/blob/main/docs/pages/index.md にて、  
図・フローチャートの画像が表示されていない。

### 使用している charcoal および周辺環境

(略)

### コード例へのリンク

(略)

### 現在の挙動

<img width="649" alt="スクリーンショット 2022-08-18 18 18 51" src="https://user-images.githubusercontent.com/725271/185359328-8143285f-3397-451a-b822-88a1d0e4ba57.png">

**Comment by fsubal** [comment]
なるほど。

`/docs` 以下ですが GitHub Pages でホスティングした際に正しく画像が出るようなパスで書かれていて、
Github 上で .md ファイルをプレビューした時のことは実は重視してなかったりします。

https://pixiv.github.io/charcoal/docs/#/?id=%e8%a8%ad%e8%a8%88%e6%80%9d%e6%83%b3

ただし styled のページは両方で上手く行っているので、このページも両立するようにはできそうですね

https://pixiv.github.io/charcoal/docs/#/pages/utilities/styled
