### ISSUE TITLE
Feat: Tooltip の実装

### ISSUE THREAD

**Issue by murokaco** [pixiv/charcoal#143]
### 必要だと思う機能の内容を書いてください

<img width="737" alt="スクリーンショット 2022-11-07 19 20 03" src="https://user-images.githubusercontent.com/1035673/200286278-91213156-9851-496d-a3b0-a7743b13f1df.png">
デザインは Figma の
[[Latest]Web Components](https://www.figma.com/file/BBn59QNBqoCwM8wTHKIydC/%5BLatest%5D-Web-Components?node-id=20152%3A8663)
をご確認ください。

(不明点は Slack で murokaco 宛にお尋ねください 🙇‍♀️) 

### この機能が必要と考えられる理由を書いてください

常に表示する必要はないが、補足テキストがないと情報が不十分な場合があるため

* 例: リンクテキストの情報だけだとユーザーがページ遷移を躊躇うのを「特典がある」と補足することで遷移を促している
<img width="1130" alt="スクリーンショット 2022-11-07 18 54 40" src="https://user-images.githubusercontent.com/1035673/200287875-0c52e3bb-467c-446d-bb44-e6d3e9712545.png">

### この機能があった場合にどういう動きをするかの例を書いてください

* 表示条件: 対象(リンクや ?アイコン など)をhover, focusする
* 配置について: defaultは対象の上に中央揃えで表示
  * ウインドウサイズよりはみ出る場合
    * 上にはみ出る場合は下に表示
    * <img width="1130" alt="スクリーンショット 2022-11-07 18 54 40" src="https://user-images.githubusercontent.com/1035673/200284949-3b651760-d7d6-489e-b1fa-68167a492d54.png">

    * 左にはみ出る場合はウインドウにあわせて左寄せで表示する
    * 右にはみでる場合はウインドウにあわせて右寄せで表示する
    * <img width="448" alt="スクリーンショット 2022-11-07 18 55 15" src="https://user-images.githubusercontent.com/1035673/200284749-07cc4460-2213-4f75-a659-8af8d43f5e1d.png">

**Comment by toshusai** [comment]
To ensure clarity in our component documentation and specifications, I'd like to proceed with adding new components more cautiously. Therefore, I'll be closing this issue for adding a component at this time.
