### ISSUE TITLE
Feat: Tag Item の実装

### ISSUE THREAD

**Issue by murokaco** [pixiv/charcoal#156]
### 必要だと思う機能の内容を書いてください

<img width="528" alt="スクリーンショット 2022-11-18 16 55 55" src="https://user-images.githubusercontent.com/1035673/202650320-7bcaab9f-831d-4eeb-82d9-84456ae6c122.png">

tagの実装をお願いします 🙇‍♀️ 

デザインは Figma の 
[[Latest]Web Components](https://www.figma.com/file/BBn59QNBqoCwM8wTHKIydC/%5BLatest%5D-Web-Components?node-id=20152%3A8663)
をご確認ください

### この機能が必要と考えられる理由を書いてください

* ユーザーがコンテンツに辿り着きやすくなる

### この機能があった場合にどういう動きをするかの例を書いてください

* タグをクリックすると
  * Default の場合: タグの一覧ページに遷移する
  * Activeの場合: タグ自体を削除する(例: https://www.pixiv.net/users/14601125/illustrations/ONEPIECE)

* background-color について
  * [Figma: Foundations](https://www.figma.com/file/yvkG3sWmgeLSOHIEiGyafR/%5BLatest%5D-Foundations---Internal?node-id=0%3A1&t=hFXOVrc8NSwQPoLl-1)にある Tag (9色)を指定できるようになっている
  * [Figmaブランチ](https://www.figma.com/file/BBn59QNBqoCwM8wTHKIydC/branch/LoqwoJ1RvS5u5ILEzI707n/%5BLatest%5D-Web-Components?node-id=20152%3A8663&t=BAJS42wrefafDVTH-1) にも例がありますが、Dafultは tag color 5 が指定してある感じです。
  * <img width="578" alt="スクリーンショット 2022-11-30 16 26 49" src="https://user-images.githubusercontent.com/1035673/204733606-8f9b50a3-120f-47dd-8c59-0afcfcc4f59a.png">

* 文字が長くなる場合はellipsisする
  * <img width="322" alt="スクリーンショット 2022-11-18 17 23 51" src="https://user-images.githubusercontent.com/1035673/202655484-282058b6-ad1d-47cc-bd0d-97e8135dc117.png">
  テキスト部分は max-width: 152px; としているようです

**Comment by murokaco** [comment]
* 背景画像があるバージョンの追加について
* pixiv.netのランダム背景色について

の仕様を策定するまで pending となりました 🙇‍♀️

**Comment by naporin0624** [comment]
text color, background color はさせるようにしておく

**Comment by murokaco** [comment]
@naporin0624 
BackgroundColorの例、こんな感じになります(descriptionにも追記しておきます)
Defaultは tag color の5 が指定してある状態です。

<img width="602" alt="スクリーンショット 2022-11-30 16 23 51" src="https://user-images.githubusercontent.com/1035673/204733250-0637ece9-fa6b-4df7-a9ce-81feba92aa66.png">

**Comment by murokaco** [comment]
@naporin0624 
口頭でご相談していた `背景に画像を指定できるようにしたい` という件ですが、
デザインの必要があるのでこのissueには含まないということでお願いします(別途issue立てます) 🙇‍♀️
