### ISSUE TITLE
Feat: Dropdown Selector に 見出しラベルを追加したい, Separatorを任意にしたい

### ISSUE THREAD

**Issue by murokaco** [pixiv/charcoal#162]
### 必要だと思う機能の内容を書いてください

<img width="699" alt="スクリーンショット 2023-02-08 19 18 09" src="https://user-images.githubusercontent.com/1035673/217502802-4fd5f9cb-3feb-4373-aaca-0ca3a8b5446d.png">

* 見出しがあるパターン(画像右)
* 見出しがないパターン(画像中央下)
  * 見出しは必要ないが、選択肢をグルーピングしたいという要望です。

(画像左、画像中央上は既に実装していただいてるものです)

### この機能が必要と考えられる理由を書いてください

選択肢が多い場合、グルーピングする必要があるため

### 見出しありパターン
HTMLで言う `optgroup` に相当するやつです。

* 見出し(1つ)、選択項目(複数)で、選択項目の最後にborder-bottomを入れてください。

### 選択項目に任意のタイミングでSeparatorを追加したいパターン

* 選択項目にborderを挟めるようになる or 選択項目にborder-bottom あり・なしパターンを指定できる(今Figma上のコンポーネントはこちらになってます)

**Comment by murokaco** [comment]
デザインの依頼はこちらで出してます
https://www.notion.so/pixiv/DropDown-Selecter-2faa3e1c24704f4f9c61d90d3d8aae9c

**Comment by naporin0624** [comment]
各要素の一番下の要素には separator をつけない

**Comment by fsubal** [comment]
Separator 任意化がまだっぽい？

**Comment by fsubal** [comment]
v3.0.0 ブランチにこの内容が反映されてない？ @toshusai
