### ISSUE TITLE
Feat: TextFieldにautofocus propを追加する

### ISSUE THREAD

**Issue by mimokmt** [pixiv/charcoal#164]
### 必要だと思う機能の内容を書いてください

HTMLのTextFieldにあるautofocusを実装する

### この機能が必要と考えられる理由を書いてください

プロダクトでrefを使ってすでに実装が行われており、特別な機能でもないのでcharcoalで実装すべきであると考えるため

### この機能があった場合にどういう動きをするかの例を書いてください

いずれかの手法がある

- HTMLのautofocusをそのまま使う
- refを使って実装、必要に応じてrefをマージできるようにする

**Comment by fsubal** [comment]
### 検討事項

- autoFocus 属性が Safari でおかしくなるみたいな挙動が以前聞かれていたが、それは今もあるのか（ある場合、ref を使って実装したほうが良い）
- 1ページに複数 autoFocus: true なコンポーネントがいる場合、どういう動きをするべきか（そもそもそう書かないでほしいが）
- ref を使う場合 `mergeRefs()` を使うことになると思うが、これは utils とかに置いて公開 API にして良いのではないか

**Comment by naporin0624** [comment]
`<input type="text" autofocus />` な html に対して挙動を検証しました。

確認に使用したページ https://sz59yk.csb.app/ 

|端末|バージョン|ブラウザ|autofocus が作動するか|
|---|---|---|---|
|iPhone|15.6.1|safari|○|
|iPhone|15.6.1|chrome|○|
|iPad|15.3.1|safari|○|
|iPad|15.3.1|chrome|○|
|windows|10|chrome|○|
|mac|12.6|chrome|○|

> autoFocus 属性が Safari でおかしくなるみたいな挙動が以前聞かれていたが、それは今もあるのか（ある場合、ref を使って実装したほうが良い）

これがどういう挙動を指しているか不明ですが、自前の環境ではおかしな挙動はしなかったです。

[caniuse](https://caniuse.com/mdn-html_global_attributes_autofocus) を参照したところ html attribute autofocus の対応率は
> 71.83%	+	23.44%	=	95.28%

でした。

> 1ページに複数 autoFocus: true なコンポーネントがいる場合、どういう動きをするべきか

- Context を使用して内部に参照カウンタを持つことで autoFocus attribute が付与されている charcoal component は1つしか存在できないみたいなことをするのはどうかなと思いました。
  - dev 環境では warning だして一番はじめの autoFocus だけが true になるようにする
  - charcoal component を使用していないところで autoFocus を使われてしまった場合検知できないので微妙

**Comment by fsubal** [comment]
Input コンポーネントに ref を加える + props を HTMLInputElement に準拠する話にマージする？

**Comment by toshusai** [comment]
With the release of version 3.0.0, it is now possible to apply autoFocus to inputs.
