### ISSUE TITLE
Feat: Tabの実装[charcoal]

### ISSUE THREAD

**Issue by murokaco** [pixiv/charcoal#232]
### 必要だと思う機能の内容を書いてください

<img width="414" alt="スクリーンショット 2023-02-15 19 07 15" src="https://user-images.githubusercontent.com/1035673/218997534-a31a4429-75b7-43e5-9f61-47880682c52f.png">

Tabの実装をお願いします 🙇‍♀️

デザインは Figma の
[[Latest]Web Components](https://www.figma.com/file/BBn59QNBqoCwM8wTHKIydC/%5BLatest%5D-Web-Components?node-id=20152%3A8663&t=LLbepTznFOGOMcgn-1)
をご確認ください

### この機能が必要と考えられる理由を書いてください

コンテンツ種別によって表示を切り替えるUIが必要なため

### この機能があった場合にどういう動きをするかの例を書いてください

* Tabをクリックすると、下のコンテンツが入れ替わる
* コンテンツはpaddingなど、中身の見え方などは一切持たない

* 横に何個表示するのか、スクロールをこちらが持つのか(→月曜日に決めます)

**Comment by toshusai** [comment]
To ensure clarity in our component documentation and specifications, I'd like to proceed with adding new components more cautiously. Therefore, I'll be closing this issue for adding a component at this time.
