### ISSUE TITLE
Bug: DropdownSelectorが複数ある時PopOverのスタイルがおかしい

### ISSUE THREAD

**Issue by toshusai** [pixiv/charcoal#233]
### できる限り詳細に、不具合の内容と再現方法を報告してください

<img width="357" alt="スクリーンショット 2023-02-17 15 27 56" src="https://user-images.githubusercontent.com/35446607/219566240-47b9a089-1b4a-4fd8-8b70-149852770f78.png">

### 使用している charcoal および周辺環境

@charcoal-ui/react@2.2.1

**Comment by naporin0624** [comment]
https://github.com/pixiv/charcoal/pull/225
これはこの修正で治るかと思います。(popover の実装が間違っていた
