### ISSUE TITLE
Q. すべてのコンポーネントは className?: string および ref を受け取るべきか

### ISSUE THREAD

**Issue by fsubal** [pixiv/charcoal#263]
# 背景

- コンポーネントによって `className?: string` を受け取ったり受け取らなかったりがある
- コンポーネントによって `forwardRef` をしてたりしてなかったりがある
- コンポーネントによって（ Web 標準に親しい内容だが ） `HTMLProps<HTMLInputElement>` に準拠してなかったりする

この点について方針が決まってないので、決めたい。

**Comment by fsubal** [comment]
一般に React コンポーネントが `className?: string` という Props を受け取ることは嫌われたりもするが、デザインシステムから外れる見た目がちょっとでも生じたらまるごと再実装を要求するのも嫌なので、エスケープハッチとしてあって良いと思っている（ styled-components の `styled(Component)` のような記法もサポートされる ）

**Comment by naporin0624** [comment]
classname を受け取るなら style は受け取るべきだと考えますか....？

**Comment by naporin0624** [comment]
テーマに沿った変更をしてほしいという気持ちがある以上 tailwind 通してもらうか styled 通して変更してほしいという気持ちを込めて className だけの方が良さそうですね
