### ISSUE TITLE
Feat: Modal内の左右paddingの調整

### ISSUE THREAD

**Issue by annin3** [pixiv/charcoal#265]
### 必要だと思う機能の内容を書いてください

[Figma](https://www.figma.com/file/BBn59QNBqoCwM8wTHKIydC/%5BLatest%5D-Web-Components?node-id=44283%3A7015&t=wEexreaDuzGMQ3SS-1)

非モバイルサイズ(width 984px以上)におけるModal内のpadding調整をお願いします。
左右のpaddingを24px→16pxに変更してください。

### この機能が必要と考えられる理由を書いてください

モバイルサイズ(width 984px未満)におけるModal内の左右paddingとの共通化のため。

**Comment by murokaco** [comment]
ご対応ありがとうございます！
