### ISSUE TITLE
Bug: アイコンの色をtext4からtext3に変更して欲しい

### ISSUE THREAD

**Issue by murokaco** [pixiv/charcoal#335]
### できる限り詳細に、不具合の内容と再現方法を報告してください

text4ではコントラスト比が低く、視認性が悪いため、text3に変更したい

該当箇所
* textfield の prefix icon: 

### 使用している charcoal および周辺環境

storybook👀

### コード例へのリンク

https://pixiv.github.io/charcoal/?path=/story/textfield--prefix-icon

**Comment by naporin0624** [comment]
storybook の対応だけでよい
