### ISSUE TITLE
Bug: CharcoalのサイトにおいてSwitchの表示がSafariだと不自然になる

### ISSUE THREAD

**Issue by kiharu3112** [pixiv/charcoal#467]
### できる限り詳細に、不具合の内容と再現方法を報告してください

ここに書くのが適切か分からなかったので、間違ってたらすいません。

https://charcoal-web.pixiv.design/@charcoal-ui/react/Switch/ をMacおよびiPadのSafariで表示した際、BasicのSwitchが表示される位置が不自然に感じました。
Safari以外のブラウザではこの事象は確認できませんでした。
<img width="1037" alt="image" src="https://github.com/pixiv/charcoal/assets/74781355/3de14087-2a40-419f-bc92-ea2e17656468">

### 使用している charcoal および周辺環境

MacOS Sonoma 14.1.2
Safari 17.1.2

iPadOS 17.4

**Comment by toshusai** [comment]
ご報告ありがとうございました。こちらの問題は #470 により修正されました。
