### ISSUE TITLE
Bug: @charcoal-ui/tailwind-config を導入すると、Tailwind CSSに通常存在するクラスが使用できなくなる

### ISSUE THREAD

**Issue by ryohidaka** [pixiv/charcoal#645]
### できる限り詳細に、不具合の内容と再現方法を報告してください

`@charcoal-ui/tailwind-config` を使用するとTailwindの標準のテーマが上書きされてしまい、`tailwind-config`内で定義されたクラスしか使用できなくなりました。

[README](https://github.com/pixiv/charcoal/tree/main/packages/tailwind-config#readme)に以下の記載があり、Tailwindの標準クラスも併用できることが本来の仕様と思われたので、Issueを作成しました。

> ### 利用できるクラス
> Tailwind.css に通常存在するクラスについては公式ドキュメントを見てください。
> 
> https://tailwindcss.com/

### 使用している charcoal および周辺環境

Viteで構築した環境に`Tailwind`と`@charcoal-ui/tailwind-config`を導入したところ再現しました。

```
"@charcoal-ui/tailwind-config": "^3.16.0",
"vite": "^5.4.9",
"tailwindcss": "^3.4.14",
```

### 現在の挙動

`theme`直下に`screens`や`colors`などのカスタムした要素が配置されています。
そのため、Tailwind標準クラスが上書きされてしまっている状態です。

https://github.com/pixiv/charcoal/blob/e28930956816f95325a648ec492d9f1f82e516c8/packages/tailwind-config/src/index.ts#L40-L106

### 期待される挙動

下記のように`extend`を挟むことで、Tailwindの標準クラスも併用できるようになります。　(Tailwind v1, v2も同様)

`packages/tailwind-config/src/index.ts`
```ts
return {
  theme: {
      extend: {
          screens: {
              ...
          },
          colors: {
              ...
          }
      }
  }
}
```

参考: https://tailwindcss.com/docs/theme#extending-the-default-theme

**Comment by mimokmt** [comment]
IssueならびにPull Requestの作成ありがとうございます。 

これは意図した仕様です。 
CharcoalではCharcoalのデザインルールで定義された定数以外を利用出来ないようにするため、Tailwind CSSの標準テーマを利用出来ないように制限しています。 
 `Tailwind.css に通常存在するクラス` と記載している意図としては上書きしていない部分について、公式ドキュメントを参照してほしいためです。

Charcoalを利用する上で必要な定義があれば #161 のように別途issueを立ててください。
